### ISSUE TITLE
Research Terraform Registry Publishing

### ISSUE THREAD

**Issue by graham-russell** [ably/terraform-provider#10]
When we are done creating the provider, we will need to publish it on the Terraform registry. 
We should scope out the process ahead of time and get any necessary sign-off. We will also need to evaluate Hashicorp's terms of use and get sign-off.

┆Issue is synchronized with this [Jira Task](https://ably.atlassian.net/browse/IAC-13) by [Unito](https://www.unito.io)

**Comment by graham-russell** [comment]
Documentation here - https://www.terraform.io/registry/providers/publishing

**Comment by graham-russell** [comment]
Terms of use here - https://registry.terraform.io/terms

**Comment by kavalerov** [comment]
Tickets opened to prepare us for publishing the provider: 
- https://github.com/ably/terraform-provider/issues/19
- https://github.com/ably/terraform-provider/issues/20
- https://github.com/ably/terraform-provider/issues/21
