### ISSUE TITLE
Build a go rest client for the control API

### ISSUE THREAD

**Issue by Morganamilo** [ably/terraform-provider#18]
┆Issue is synchronized with this [Jira Task](https://ably.atlassian.net/browse/IAC-23) by [Unito](https://www.unito.io)

**Comment by Morganamilo** [comment]
Lewis has a prototype here that can be built of off https://github.com/ably/ably-cli-prototype/tree/main/go/controlapi

**Comment by kavalerov** [comment]
Do we know what repo we will build it in?

**Comment by kavalerov** [comment]
It also would be great to scope this a bit more if that's ok, and potentially split into several sub-issues, i.e. "Set up repo and testing infrastructure", "Implement authentication", "Implement `apps` endpoint", "Implement `rules` endpoint". Happy to help with the admin side of this!

**Comment by Morganamilo** [comment]
This will probably be owned by the sdk team under something like ably-control-go. I don't think we need separate issues for each end point as they're small and not a lot of work.

I am for separate issues for the admin work but I would like to do that once we get a repo set up.

**Comment by kavalerov** [comment]
For traceability - closed as Go Control API client is being developed here now: https://github.com/ably/ably-control-go
